apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-canary-rollout
  namespace: canary
spec:
  replicas: 1
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 100s}
        - setWeight: 50
        - pause: {duration: 100s}
        - setWeight: 100
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80
