apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-git
spec:
  generators:
    - git:
        repoURL: 'https://github.com/jiheon2/ArgoCD.git'
        revision: main
        directories:
          - path: sample/overlays/rollout/*
  template:
    metadata:
      name: applicationset-cluster
    spec:
      project: default
      source:
        repoURL: 'https://github.com/jiheon2/ArgoCD.git'
        targetRevision: main
        path: sample/base
      destination:
        name: in-cluster
        namespace: applicationset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
