apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-list
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            path: sample/base
          - cluster: sub-cluster
            path: sample/base
  template:
    metadata:
      name: applicationset-list
    spec:
      project: default
      source:
        repoURL: 'https://github.com/jiheon2/ArgoCD.git'
        targetRevision: main
        path: sample/base
      destination:
        name: in-cluster
        namespace: applicationset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
