apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-matrix
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - { cluster: in-cluster }
                - { cluster: sub-cluster }
          - git:
              repoURL: 'https://github.com/jiheon2/ArgoCD.git'
              revision: main
              directories:
                - path: 'sample/base'
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/jiheon2/ArgoCD.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        name: '{{cluster}}'
        namespace: applicationset-matrix
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
