apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sub-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: latest
    helm:
      values: |
        replicaCount: 2
        service:
          type: ClusterIP
  destination:
    server: https://192.168.0.104:6443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true