apiVersion: v1
kind: Service
metadata:
  name: test-63
  labels:
    app: test
  namespace: default
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8099
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-63
  labels:
    app: test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: 34.22.79.12:30003/source/test-image:v63
          ports:
            - containerPort: 80
