apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-cluster
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: test
  template:
    metadata:
      name: applicationset-cluster
    spec:
      project: default
      source:
        repoURL: 'https://github.com/jiheon2/ArgoCD.git'
        targetRevision: main
        path: sample/base
        directory:
          recurse: true
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: applicationset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
